package model;
// Generated Jun 4, 2014 3:58:00 PM by Hibernate Tools 3.6.0

import java.io.File;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Arquivo generated by hbm2java
 */
public class Arquivo implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;
    private String name;
    private String extension;
    private String directory;

    /**
     * File source
     */
    private File file;

    public Arquivo() {
    }

    public Arquivo(String name, String extension, String directory) {
        this.name = name;
        this.extension = extension;
        this.directory = directory;
    }

    /**
     * Custom constructor
     */
    public Arquivo(int id, String name, String ext, String dir) {
        this.id = id;
        this.name = name;
        this.extension = ext;
        this.directory = dir;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getExtension() {
        return this.extension;
    }

    public void setExtension(String extension) {
        this.extension = extension;
    }

    public String getDirectory() {
        return this.directory;
    }

    public void setDirectory(String directory) {
        this.directory = directory;
    }

}
