package model;
// Generated Jun 21, 2014 3:59:06 PM by Hibernate Tools 3.6.0



/**
 * Biblioteca generated by hbm2java
 */
public class Biblioteca  implements java.io.Serializable {


     private Integer id;
     private String nome;

    public Biblioteca() {
    }

    public Biblioteca(String nome) {
       this.nome = nome;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }




}


