package model;
// Generated Jun 7, 2014 1:46:42 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Set componentes = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(String nome) {
        this.nome = nome;
    }
    public Categoria(String nome, Set componentes) {
       this.nome = nome;
       this.componentes = componentes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getComponentes() {
        return this.componentes;
    }
    
    public void setComponentes(Set componentes) {
        this.componentes = componentes;
    }
    
    @Override
    public String toString() {
        return this.nome;
    }  

    public Object[] toArray() {
        return new Object[]{this,this.getNome()};
    }

}


