package model;
// Generated Jun 21, 2014 2:08:36 AM by Hibernate Tools 3.6.0



/**
 * Framework generated by hbm2java
 */
public class Framework  implements java.io.Serializable {


     private Integer id;
     private String nome;

    public Framework() {
    }

    public Framework(String nome) {
       this.nome = nome;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }




}


