package view;

import control.FileControl;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.ErrorView;

public class FileManagerWin extends javax.swing.JDialog {

    FileControl ctr;
    ArrayList files;
    int row_selected;
    int opt_select = 0;
    List list = null;

    public FileManagerWin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        try {
            // Control
            ctr = new FileControl();

            // Loading files in the table
            ctr.loadingAllFilesInTable(file_list);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO não esperado. " + e.getMessage());
        }
    }

    /**
     * Select option
     *
     * @param parent
     * @param modal
     */
    public FileManagerWin(java.awt.Frame parent, boolean modal, boolean select) {
        super(parent, modal);
        initComponents();

        try {
            // Control
            ctr = new FileControl();

            // Loading files in the table
            ctr.loadingAllFilesInTable(file_list);

            // Enable select button
            if (select) {
                this.opt_select = 1;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO não esperado. " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        file_list = new javax.swing.JTable();
        btn_search = new javax.swing.JToggleButton();
        input_search = new javax.swing.JTextField();
        search_type = new javax.swing.JComboBox();
        btn_alter = new javax.swing.JToggleButton();
        btn_select = new javax.swing.JToggleButton();
        add_component = new javax.swing.JToggleButton();
        btn_delete = new javax.swing.JToggleButton();
        btn_atualizar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciador de Arquivos");
        setResizable(false);

        file_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Extensão", "Diretório"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        file_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                file_listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(file_list);

        btn_search.setText("Pesquisar");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        input_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_searchActionPerformed(evt);
            }
        });

        search_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID", "Nome", "Extensão" }));
        search_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_typeActionPerformed(evt);
            }
        });

        btn_alter.setText("Alterar");
        btn_alter.setEnabled(false);
        btn_alter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterActionPerformed(evt);
            }
        });

        btn_select.setText("Selecionar");
        btn_select.setEnabled(false);
        btn_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selectActionPerformed(evt);
            }
        });

        add_component.setText("Adicionar");
        add_component.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_componentActionPerformed(evt);
            }
        });

        btn_delete.setText("Excluir");
        btn_delete.setBorderPainted(false);
        btn_delete.setEnabled(false);
        btn_delete.setFocusPainted(false);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_atualizar.setText("Atualizar");
        btn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(search_type, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_search)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_search))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_atualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_select)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_alter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add_component)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(input_search)
                    .addComponent(search_type, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btn_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_component, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_alter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_select, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_alterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterActionPerformed

        FileWin win_file = null;

        try {
            // Get file ID
            int file_id = Integer.parseInt(file_list.getValueAt(this.row_selected, 0).toString());

            // Build windows
            win_file = new FileWin(file_id, null, true);

            win_file.setLocationRelativeTo(null);
            win_file.setVisible(true);

            this.refreshTable();

        } catch (Exception ex) {
            ErrorView.errorDefault(ex);
        }

    }//GEN-LAST:event_btn_alterActionPerformed

    private void btn_selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selectActionPerformed

        this.list = new ArrayList();

        // Pega a quantiade de linhas selecionadas
        int list_size = file_list.getSelectedRows().length;

        // Pega as linhas selecionadas
        int[] list_file = file_list.getSelectedRows();

        // Salva os IDs na list
        for (int i = 0; i < list_size; i++) {
            this.list.add(Integer.parseInt(file_list.getValueAt(list_file[i], 0).toString()));
        }

        this.setVisible(false);

    }//GEN-LAST:event_btn_selectActionPerformed

    private void add_componentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_componentActionPerformed

        FileWin win_file = null;

        try {
            win_file = new FileWin(null, true);

            btn_alter.setEnabled(false);
            btn_delete.setEnabled(false);
            btn_select.setEnabled(false);
        } catch (Exception ex) {
            Logger.getLogger(FileManagerWin.class.getName()).log(Level.SEVERE, null, ex);
        }

        win_file.setLocationRelativeTo(null);
        win_file.setVisible(true);

        try {
            this.refreshTable();
        } catch (Exception ex) {
            Logger.getLogger(FileManagerWin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_add_componentActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed

        try {
            // Delete file
            int file_id = Integer.parseInt(file_list.getValueAt(this.row_selected, 0).toString());
            ctr.delete(file_id);

            this.refreshTable();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO ao excluir. " + e.getMessage());
        }

    }//GEN-LAST:event_btn_deleteActionPerformed

    private void input_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_searchActionPerformed

    private void file_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_file_listMouseClicked

        this.row_selected = file_list.getSelectedRow();

        if (this.row_selected >= 0) {

            if (this.opt_select == 1) {
                btn_select.setEnabled(true);
            } else {

                // Enable buttons
                btn_delete.setEnabled(true);
                btn_alter.setEnabled(true);

            }

        }

    }//GEN-LAST:event_file_listMouseClicked

    private void btn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizarActionPerformed

        try {
            this.refreshTable();
        } catch (Exception ex) {
            Logger.getLogger(FileManagerWin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_atualizarActionPerformed

    private void search_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_typeActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed

        try {

            if ("".equals(input_search.getText())) {
                JOptionPane.showMessageDialog(this, "Você precisa informar o que quer pesquisar!");
            } else {
                ctr.search(file_list, search_type.getSelectedIndex(), input_search.getText());
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ERRO ao PESQUISAR. " + ex.getMessage());
        }

    }//GEN-LAST:event_btn_searchActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileManagerWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileManagerWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileManagerWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileManagerWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FileManagerWin dialog = new FileManagerWin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    /**
     * Atualiza a tabela
     *
     * @throws Exception
     */
    public void refreshTable() throws Exception {

        // Clean selection
        file_list.clearSelection();

        // Clean table
        for (int i = file_list.getRowCount() - 1; i >= 0; i--) {
            ((DefaultTableModel) file_list.getModel()).removeRow(i);
        }

        // Loading files in the table
        ctr.loadingAllFilesInTable(file_list);

        // Check list is empty 
        if (file_list.getRowCount() == 0) {
            btn_alter.setEnabled(false);
            btn_delete.setEnabled(false);
            btn_select.setEnabled(false);
        }

        // Clean search input
        input_search.setText("");
    }

    public List getList() {
        return this.list;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton add_component;
    private javax.swing.JToggleButton btn_alter;
    private javax.swing.JToggleButton btn_atualizar;
    private javax.swing.JToggleButton btn_delete;
    private javax.swing.JToggleButton btn_search;
    private javax.swing.JToggleButton btn_select;
    private javax.swing.JTable file_list;
    private javax.swing.JTextField input_search;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox search_type;
    // End of variables declaration//GEN-END:variables
}
