package view;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.channels.FileChannel;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Arquivo;
import model.Componente;
import model.FileManager;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() throws IOException {
        initComponents();

        // Montando arquivos
        //Arquivo arquivo = new Arquivo(1, "teste", "txt");
        //Arquivo arquivo_2 = new Arquivo(2, "teste", "txt");
        // Iniciando um novo componente
        //Componente menu = new Componente(1, "Menu", 3, 50);
        //menu.getArquivos().add(arquivo);
        //menu.getArquivos().add(arquivo_2);
        //Iterator item = menu.getArquivos().iterator();  
        //while (item.hasNext()) {  
        //   System.out.println(item.next());  
        //}  
//        File diretorioRaiz = new File("/teste");
//        File arquivo1 = new File(diretorioRaiz, "autoexec.bat");
//
//        diretorioRaiz.mkdirs();
//
//        if (arquivo1.exists()) {
//            System.out.println("Existe");
//        } else {
//            System.out.println("Não existe");
//        }
//        
//        File source = new File("/teste/teste1.txt");
//                
//        File destination = new File("/copiateste/teste1.txt");
//        
//        Arquivo.copyFile(source, destination);
        
 

        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
