package dao.hibernate;
// Generated Jun 1, 2014 5:37:10 PM by Hibernate Tools 3.6.0



/**
 * LmFile generated by hbm2java
 */
public class LmFile  implements java.io.Serializable {


     private Integer idFile;
     private String name;
     private String extension;
     private String fileName;

    public LmFile() {
    }

    public LmFile(String name, String extension, String fileName) {
       this.name = name;
       this.extension = extension;
       this.fileName = fileName;
    }
   
    public Integer getIdFile() {
        return this.idFile;
    }
    
    public void setIdFile(Integer idFile) {
        this.idFile = idFile;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getExtension() {
        return this.extension;
    }
    
    public void setExtension(String extension) {
        this.extension = extension;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }




}


